cerad_app_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CeradAppBundle:Default:index }
    
cerad_app_index:
  path:  /
  defaults: 
    _controller: cerad_app__index__controller:action
